import { useEffect, useMemo, useState } from "react";

type LiveData={temperature:number;humidity:number;wind:number;pm10:number;pm25:number;status:"live"|"static"};
const DATA_MODE=import.meta.env.VITE_DATA_MODE==="live"?"live":"static";
const energy=[142,176,214,258,301,338];
const districts=[{n:"Mitte",v:[23,17,29]},{n:"Kreuzberg",v:[18,24,34]},{n:"Charlottenburg",v:[25,20,28]},{n:"Neukölln",v:[15,27,31]},{n:"Pankow",v:[20,18,36]}];
const chargers=[["Alexanderplatz","Available","22 kW"],["Potsdamer Platz","2 in use","150 kW"],["Hauptbahnhof","Available","50 kW"],["Tempelhof","Maintenance","22 kW"]];

function Ring({value,label,sub,tone="cyan"}:{value:number;label:string;sub:string;tone?:string}){return <div className={`ring ${tone}`} style={{"--value":`${value*3.6}deg`} as React.CSSProperties}><div><strong>{value}</strong><span>{label}</span><small>{sub}</small></div></div>}
function Head({tag,title,side}:{tag:string;title:string;side?:React.ReactNode}){return <header><div><span className="kicker">{tag}</span><h2>{title}</h2></div>{side??<button aria-label="More options">•••</button>}</header>}

const Kpi=({label,value,unit,delta}:{label:string;value:string;unit:string;delta:string})=><article className="domainKpi"><span>{label}</span><strong>{value}<small>{unit}</small></strong><em>{delta}</em></article>;
const Spark=({values}:{values:number[]})=><div className="spark">{values.map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div>;

function MobilityView(){const routes=[["U2","Pankow → Ruhleben","96%","On time"],["M4","Falkenberg → Hbf","88%","Minor delay"],["S7","Ahrensfelde → Potsdam","92%","On time"],["Bus 100","Alexanderplatz → Zoo","81%","Crowded"]];return <>
 <div className="domainIntro"><div><span className="kicker">NETWORK COMMAND / MOBILITY</span><h2>Movement across the city</h2><p>One operating picture for transit, road flow, shared mobility and curb infrastructure.</p></div><div className="modeSwitch"><button className="active">LIVE</button><button>24 HOURS</button><button>7 DAYS</button></div></div>
 <div className="kpiStrip span5"><Kpi label="DAILY JOURNEYS" value="3.82" unit="M" delta="↑ 4.1% vs. Tuesday"/><Kpi label="NETWORK SPEED" value="31.6" unit="km/h" delta="↑ 2.4 km/h"/><Kpi label="ON-TIME TRANSIT" value="93.4" unit="%" delta="↑ 1.8 points"/><Kpi label="SHARED VEHICLES" value="18.7" unit="k" delta="12,421 available"/></div>
 <article className="panel span3 mobilityMap"><Head tag="LIVE NETWORK" title="Mobility flow map" side={<span className="source live"><i/>UPDATING</span>}/><div className="cityMap"><div className="river"/><div className="road r1"/><div className="road r2"/><div className="road r3"/><div className="road r4"/>{[[20,20,"A"],[45,38,"H"],[70,24,"P"],[74,70,"T"],[28,72,"K"],[53,58,"M"]].map(([x,y,n])=><button key={n} style={{left:`${x}%`,top:`${y}%`}}><i/>{n}</button>)}<span className="mapCallout"><b>Alexanderplatz</b><small>24 km/h · normal flow</small></span></div><footer><span><i className="key green"/>Free flow</span><span><i className="key orange"/>Dense</span><span><i className="key violet"/>Transit hub</span></footer></article>
 <article className="panel span2"><Head tag="PUBLIC TRANSPORT" title="Route performance"/><div className="routeTable">{routes.map(([id,route,pct,state])=><div key={id}><b>{id}</b><span>{route}</span><em>{pct}</em><small className={state==="On time"?"goodText":"warnText"}>{state}</small></div>)}</div><div className="capacity"><span>AVERAGE OCCUPANCY</span><strong>64%</strong><div><i style={{width:"64%"}}/></div></div></article>
 <article className="panel span2"><Head tag="TRAFFIC ANALYTICS" title="Hourly road speed"/><div className="hourChart"><Spark values={[72,68,55,42,31,38,52,66,74,79,76,69]}/><div><span>06</span><span>09</span><span>12</span><span>15</span><span>18</span><span>21</span></div></div><footer><b>Evening peak easing 18 min earlier</b></footer></article>
 <article className="panel"><Head tag="CURB & PARKING" title="Availability"/><Ring value={68} label="AVAILABLE" sub="8,416 SPACES" tone="limeTone"/><div className="microList"><span>Street <b>71%</b></span><span>Garages <b>62%</b></span><span>Loading zones <b>84%</b></span></div></article>
 <article className="panel span2"><Head tag="ACTIVE TRAVEL" title="Cycling pulse"/><div className="bigStat"><strong>128,482</strong><span>bike movements today</span></div><Spark values={[22,18,25,44,71,82,64,51,74,88,69,42,31,21]}/><footer><span>Peak 08:20</span><b>+9.2% week on week</b></footer></article>
 </>}

function EnergyView(){return <>
 <div className="domainIntro"><div><span className="kicker">GRID COMMAND / ENERGY</span><h2>Supply, demand and flexibility</h2><p>Live balancing view across distributed generation, storage and district demand.</p></div><div className="modeSwitch"><button className="active">REAL TIME</button><button>FORECAST</button><button>MARKET</button></div></div>
 <div className="kpiStrip span5"><Kpi label="SYSTEM DEMAND" value="412" unit="MW" delta="↓ 3.2% from peak"/><Kpi label="RENEWABLE SHARE" value="73" unit="%" delta="↑ 8 points today"/><Kpi label="STORAGE STATE" value="81" unit="%" delta="2h 34m reserve"/><Kpi label="GRID FREQUENCY" value="50.01" unit="Hz" delta="Within target"/></div>
 <article className="panel span3"><Head tag="24-HOUR OUTLOOK" title="Demand & generation forecast" side={<span className="source live"><i/>MODEL 18:30</span>}/><div className="forecast"><div className="forecastArea"/><div className="forecastLine"/><Spark values={[42,38,34,31,35,48,66,78,85,81,73,69,71,76,84,92,88,79,68,61,55,49,45,43]}/><div className="forecastLabels"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>24:00</span></div></div><footer><span><i className="key cyan"/>Demand</span><span><i className="key green"/>Renewables</span><b>Forecast confidence 94%</b></footer></article>
 <article className="panel span2"><Head tag="GENERATION FLEET" title="Live production"/><div className="sourceMix">{[["Solar","208","68%"],["Wind","94","31%"],["Biogas","26","9%"],["CHP","51","17%"]].map(([n,v,p],i)=><div key={n}><span><i className={`mix${i}`}/>{n}</span><strong>{v}<small> MW</small></strong><div><i style={{width:p}}/></div></div>)}</div></article>
 <article className="panel span2"><Head tag="FLEXIBILITY" title="Battery fleet"/><div className="battery"><div><i style={{height:"81%"}}/><span>81%</span></div><section><strong>246 MWh</strong><span>Available capacity</span><strong>+38 MW</strong><span>Charging now</span></section></div><footer><b>14 sites responding</b></footer></article>
 <article className="panel"><Head tag="GRID QUALITY" title="Stability"/><Ring value={99} label="STABLE" sub="50.01 HZ" tone="limeTone"/><div className="microList"><span>Voltage <b>Nominal</b></span><span>Reserve <b>18.2%</b></span></div></article>
 <article className="panel span2"><Head tag="DISTRICT LOAD" title="Demand ranking"/><div className="rankList">{[["Mitte",88],["Charlottenburg",76],["Neukölln",71],["Pankow",64],["Kreuzberg",58]].map(([n,v])=><div key={n}><span>{n}</span><div><i style={{width:`${v}%`}}/></div><b>{v} MW</b></div>)}</div></article>
 </>}

function EnvironmentView({live}:{live:LiveData}){return <>
 <div className="domainIntro"><div><span className="kicker">URBAN ECOLOGY / ENVIRONMENT</span><h2>Climate and environmental health</h2><p>Street-level intelligence for air, heat, noise, water and city resilience.</p></div><div className="modeSwitch"><button className="active">NOW</button><button>FORECAST</button><button>SEASON</button></div></div>
 <div className="kpiStrip span5"><Kpi label="AIR QUALITY INDEX" value="32" unit="AQI" delta="Good across 82% of city"/><Kpi label="URBAN TEMPERATURE" value={`${live.temperature}`} unit="°C" delta="1.8° above rural edge"/><Kpi label="NOISE EXPOSURE" value="58" unit="dB" delta="↓ 2 dB since 17:00"/><Kpi label="WATER RESERVE" value="74" unit="%" delta="26 days at current use"/></div>
 <article className="panel span3 envMap"><Head tag="SENSOR NETWORK" title="Environmental conditions" side={<span className="source live"><i/>LIVE</span>}/><div className="heatMap">{Array.from({length:48},(_,i)=><i key={i} style={{opacity:.18+((i*7)%10)/14}}/>)}<div className="heatLegend"><span>COOL</span><i/><span>HOT</span></div><button style={{left:"23%",top:"32%"}}>18°</button><button style={{left:"58%",top:"48%"}}>22°</button><button style={{left:"76%",top:"24%"}}>20°</button></div><footer><span>Surface temperature composite</span><b>Updated 4 min ago</b></footer></article>
 <article className="panel span2"><Head tag="AIR MONITORING" title="Pollutant profile"/><div className="pollutants">{[["PM10",live.pm10,40],["PM2.5",live.pm25,24],["NO₂",18,45],["O₃",41,68]].map(([n,v,p])=><div key={n}><span>{n}</span><strong>{v}<small> µg/m³</small></strong><div><i style={{width:`${p}%`}}/></div><em>WHO guideline</em></div>)}</div><p className="api">PM data is live via Open-Meteo; remaining values are illustrative.</p></article>
 <article className="panel span2"><Head tag="CLIMATE ADAPTATION" title="Heat resilience"/><div className="resilience"><Ring value={78} label="RESILIENCE" sub="CITY INDEX" tone="limeTone"/><div className="microList"><span>Tree canopy <b>31%</b></span><span>Cool roofs <b>18.4 km²</b></span><span>Cooling sites <b>142</b></span></div></div></article>
 <article className="panel"><Head tag="ACOUSTIC CITY" title="Noise now"/><div className="noise"><strong>58</strong><span>dB average</span>{[55,38,72,49,66,42,59,34,61,46,52,40].map((v,i)=><i key={i} style={{height:v/2}}/>)}</div><footer><b>Within evening target</b></footer></article>
 <article className="panel span2"><Head tag="WATER SYSTEM" title="Consumption & reserve"/><div className="water"><div><strong>184</strong><span>litres / resident / day</span></div><div className="waterTank"><i style={{height:"74%"}}/><b>74%</b></div><div><strong>−6.4%</strong><span>versus seasonal baseline</span></div></div></article>
 </>}

export default function App(){
 const [now,setNow]=useState(new Date()); const [section,setSection]=useState("Overview");
 const [live,setLive]=useState<LiveData>({temperature:21,humidity:48,wind:12,pm10:14,pm25:8,status:"static"});
 useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(DATA_MODE!=="live")return;Promise.all([fetch("https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.405&current=temperature_2m,relative_humidity_2m,wind_speed_10m").then(r=>r.json()),fetch("https://air-quality-api.open-meteo.com/v1/air-quality?latitude=52.52&longitude=13.405&current=pm10,pm2_5").then(r=>r.json())]).then(([w,a])=>setLive({temperature:Math.round(w.current.temperature_2m),humidity:Math.round(w.current.relative_humidity_2m),wind:Math.round(w.current.wind_speed_10m),pm10:Math.round(a.current.pm10),pm25:Math.round(a.current.pm2_5),status:"live"})).catch(()=>{})},[]);
 const day=useMemo(()=>now.toLocaleDateString("en-GB",{weekday:"long",day:"2-digit",month:"long"}),[now]);
 return <div className="cockpit">
  <aside className="rail"><button className="brand" aria-label="City operations home"><span>CITY</span><b>/OPS</b></button><nav aria-label="Cockpit sections">{[["Overview","▦"],["Mobility","↝"],["Energy","ϟ"],["Environment","◌"],["Infrastructure","⌂"]].map(([x,i])=><button key={x} className={section===x?"active":""} onClick={()=>setSection(x)} title={x}>{i}</button>)}</nav><div className="railBottom"><i/>SYS<br/>ONLINE</div></aside>
  <main><div className="topbar"><div><span className="eyebrow">BERLIN / URBAN OPERATIONS</span><h1>{section === "Overview" ? "City cockpit" : `${section} command`}</h1></div><nav>{["Overview","Mobility","Energy","Environment"].map(x=><button key={x} className={section===x?"active":""} onClick={()=>setSection(x)}>{x}</button>)}</nav><div className="actions"><span className={`source ${live.status}`}><i/>{live.status==="live"?"LIVE DATA":"STATIC DATA"}</span><button>◎<b>3</b></button><button>⌘</button></div></div>
  <section className="summary"><div className="clock"><strong>{now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</strong><span>{day}</span></div><div className="weather"><b>☼</b><div><strong>{live.temperature}°</strong><span>Clear · feels like {live.temperature-1}°</span></div></div><div className="quick"><span>HUMIDITY<strong>{live.humidity}%</strong></span><span>WIND<strong>{live.wind} km/h</strong></span><span>GRID STATUS<strong className="ok">STABLE</strong></span></div><div className="score"><span>CITY PERFORMANCE</span><strong>87.4</strong><small>+2.6 this week</small></div></section>
  <section className="grid">{section === "Mobility" ? <MobilityView/> : section === "Energy" ? <EnergyView/> : section === "Environment" ? <EnvironmentView live={live}/> : <>
   <article className="panel chargers"><Head tag="MOBILITY NETWORK" title="EV charging"/><div className="chargerTop"><Ring value={76} label="AVAILABLE" sub="19 OF 25 PORTS"/><div className="legend"><p><i className="lime"/>19 available</p><p><i className="blue"/>5 in use</p><p><i className="grey"/>1 offline</p></div></div><div className="chargerList">{chargers.map(([n,s,p])=><div key={n}><i className={s==="Available"?"free":s==="Maintenance"?"down":"busy"}/><b>{n}</b><small>{p}</small><em>{s}</em></div>)}</div></article>
   <article className="panel span2"><Head tag="ENERGY GENERATION" title="Solar output" side={<div className="metric"><strong>338</strong><span>MWh today</span></div>}/><div className="solarChart"><div className="target"/>{energy.map((v,i)=><div key={v}><i style={{height:v/3.5}}/><b style={{height:(v+18)/3.5}}/><small>{2021+i}</small></div>)}</div><footer><span><i className="key cyan"/>Actual generation</span><span><i className="key dash"/>Target curve</span><b>+12.4% YOY</b></footer></article>
   <article className="panel span2"><Head tag="DISTRICT DEMAND" title="Energy consumption" side={<div className="metric"><strong>412</strong><span>MW current</span></div>}/><div className="stackChart">{districts.map(d=><div key={d.n}><section>{d.v.map((v,i)=><i key={i} style={{height:v*1.7}}/>)}</section><small>{d.n}</small></div>)}</div><footer><span><i className="key cyan"/>Civic</span><span><i className="key green"/>Transit</span><span><i className="key violet"/>Residential</span></footer></article>
   <article className="panel air"><Head tag="ENVIRONMENT" title="Air quality" side={<span className="source live"><i/>LIVE</span>}/><div className="aqi"><strong>32</strong><div><b>GOOD</b><span>Berlin average AQI</span></div></div><div className="airGrid">{[["PM10",live.pm10],["PM2.5",live.pm25],["NO₂",18],["O₃",41]].map(([x,v])=><div key={x}><span>{x}</span><strong>{v}</strong><small>µg/m³</small></div>)}</div><p className="api">Weather & air quality via Open-Meteo public APIs</p></article>
   <article className="panel span2"><Head tag="LIVE ENERGY FLOW" title="Distribution mix" side={<span className="source live"><i/>SYNCED</span>}/><div className="flow"><div className="node"><span>☼</span><strong>208</strong><small>Solar MW</small></div><div className="node"><span>≈</span><strong>94</strong><small>Wind MW</small></div><i className="line l1"/><i className="line l2"/><Ring value={73} label="RENEWABLE" sub="ENERGY SHARE" tone="limeTone"/><i className="line l3"/><div className="node demand"><span>⌁</span><strong>412</strong><small>Demand MW</small></div></div></article>
   <article className="panel emissions"><Head tag="CLIMATE" title="CO₂ emissions"/><div className="donut"><div><strong>184</strong><span>tCO₂e today</span></div></div><div className="emLegend">{[["Households","42%"],["Transport","31%"],["Industry","19%"],["Civic","8%"]].map(([a,b])=><span key={a}><i/>{a}<b>{b}</b></span>)}</div></article>
   <article className="panel span2 alerts"><Head tag="OPERATIONS FEED" title="Alerts & events" side={<button className="textBtn">VIEW ALL →</button>}/><div>{[["watch","18:24","Grid load forecast above 82% in Mitte"],["good","18:18","Air quality improved at Station 04"],["info","18:05","Tram M4 operating at normal frequency"]].map(([l,t,x])=><section key={t}><i className={l}/><time>{t}</time><p>{x}</p><button>↗</button></section>)}</div></article>
   <article className="panel pulse"><Head tag="SYSTEM HEALTH" title="City pulse" side={<span className="source live"><i/>NOMINAL</span>}/><div className="orbit"><i/><i/><i/><i/><div><strong>96</strong><span>% healthy</span></div></div><div className="pulseStats"><span>1,284<small>Sensors</small></span><span>99.98%<small>Uptime</small></span><span>42 ms<small>Latency</small></span></div></article></>}
  </section></main>
 </div>
}
